include $(PWD)/Config

all: driver

driver:
	make -C $(KERNELDIR) SUBDIRS=$(PWD)/cpc-xt modules

inodes:
	for i in 0 1 2 3; do\
		if \
			mknod -m 666 /dev/cpc_xt$$i c 126 $$i; then   \
			echo "/dev/cpc_xt$$i created"; \
		fi \
	done;
												

install:
	install -d -o root -g root -m 644 /lib/modules/`uname -r`/misc; \
	install -o root -g root -m 644 cpc-xt.ko /lib/modules/`uname -r`/misc;\
	
clean:
	 make -C $(KERNELDIR) SUBDIRS=$(PWD)/cpc-xt clean
	 rm -f .cpc-*.cmd *.ko *.o 
