include ../Config

install: cpclib.3 floader.1
	install -o root -g root -m 444 cpclib.3 $(MANPATH)/man3
	install -o root -g root -m 444 floader.1 $(MANPATH)/man1
	install -o root -g root -m 444 cpctool.1 $(MANPATH)/man1

	install -o root -g root -m 444 CPC_AddHandler.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_AddHandlerEx.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_CANExit.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_CANInit.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_ClearMSGQueue.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_CloseChannel.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_Control.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_GetCANParams.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_GetCANState.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_GetInfo.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_GetInitParamsPtr.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_GetMSGQueueCnt.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_Handle.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_OpenChannel.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_RemoveHandler.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_RemoveHandlerEx.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_RequestCANParams.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_RequestCANState.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_RequestInfo.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_SendMsg.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_SendRTR.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_SendXMsg.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_SendXRTR.3 $(MANPATH)/man3
	install -o root -g root -m 444 CPC_WaitForMType.3 $(MANPATH)/man3
