#! /usr/bin/python
#
# Generate CPCCONF.INI
#
# Copyright (C) 2000-2008 EMS Dr. Thomas Wuensche
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# start at channel 0
channelcount=0

print "; Automatically generated by generate_cpcconf.python version 1.002"

# CPC-PCI
# open the CPC-PCI information file
try:
	f=open('/proc/driver/cpc-pci/info', 'r')
	
	done=0
	while done == 0:
		# every line describes one channel
		str = f.readline()
		if str == '':
			done = 1
			continue
		# split the line into an array
		s = str.split(' ')
		# generate output for this channel
		print "[CHAN%2.2d]" % channelcount
		print "InterfaceType=CPC-PCI"
		print "SlotNr=%d" % int(s[3])
		print "BusNr=%d" % int(s[2])
		print "ChannelNr=%d\n" % int(s[1])
		# next channel
		channelcount = channelcount + 1
	# close this file
	f.close()
except:
	pass

# CPC-XT
# open the CPC-XT information file
try:
	f=open('/proc/driver/cpc-xt/info', 'r')
	
	done=0
	while done == 0:
		# every line describes one channel
		str = f.readline()
		if str == '':
			done = 1
			continue
		# split the line into an array
		s = str.split(' ')
		# generate output for this channel
		print "; Please change IrqNr to fit your needs"
		print "[CHAN%2.2d]" % channelcount
		print "InterfaceType=CPC-XT1000"
		print "ChannelNr=%d" % int(s[1])
		print "IrqNr=%d" % int(s[2])
		print "BaseAddress=%s" % s[3]
		# next channel
		channelcount = channelcount + 1
	# close this file
	f.close()
except:
	pass

# CPC-USB
# open the CPC-USB information file
try:
	f=open('/proc/driver/cpc-usb/info', 'r')
	
	done=0
	while done == 0:
		# every line describes one channel
		str = f.readline()
		if str == '':
			done = 1
			continue
		# split the line into an array
		s = str.split(' ')
		# generate output for this channel
		print "[CHAN%2.2d]" % channelcount
		print "InterfaceType=CPC-USB"
		print "SerialNumber=%d\n" % int(s[1])
		# next channel
		channelcount = channelcount + 1
	# close this file
	f.close()
except:
	pass

# CPC-CARD
# open the CPC-CARD information file
try:
	f=open('/proc/driver/cpc-card/info', 'r')
	
	done=0
	while done == 0:
		# every line describes one channel
		str = f.readline()
		if str == '':
			done = 1
			continue
		# split the line into an array
		s = str.split(' ')
		# generate output for this channel
		print "[CHAN%2.2d]" % channelcount
		print "InterfaceType=CPC-CARD"
		# currently not used
		print "PortNr=0"
		print "SlotNr=%d" % int(s[2])
		print "ChannelNr=%d\n" % int(s[1])
		# next channel
		channelcount = channelcount + 1
	# close this file
	f.close()
except:
	pass

# CPC-ECO
# open the CPC-ECO information file
try:
	f=open('/proc/driver/cpc-eco/info', 'r')
	
	done=0
	while done == 0:
		# every line describes one channel
		str = f.readline()
		if str == '':
			done = 1
			continue
		# split the line into an array
		s = str.split(' ')
		# generate output for this channel
		print "[CHAN%2.2d]" % channelcount
		print "InterfaceType=CPC-PP/ECO"
		print "PrinterPortNr=%d\n" % (int(s[1])+1)
		# next channel
		channelcount = channelcount + 1
	# close this file
	f.close()
except:
	pass

# generate 2 dummy entries only to show how it works
print "[CHAN%2.2d]" % channelcount
print "InterfaceType=ETHERCAN"
print "IpAddress=192.168.0.94"
print "IpPort=1500\n"
	
channelcount = channelcount + 1

print "[CHAN%2.2d]" % channelcount
print "InterfaceType=CPC-USB"
print "SerialNumber=9999999"

# important cause the parser required an EOF
print ''

